Vagrant.configure("2") do |config|
    config.vm.box="ubuntu/jammy64"
    config.vm.provider="Virtualbox" do |vb|
        vb.memory="1024"
        vb.cpus="1"
    end
    config.vm.network"forwarded_port",guest:"22",host:"8080"
    config.vm.network"private_network",ip:"192.168.56.1"
end